# Generated by Django 5.2.8 on 2025-11-16 07:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('target_time', models.TimeField(blank=True, null=True)),
                ('activity', models.CharField(help_text='Ej: desfile, concierto, partido, etc.', max_length=200)),
                ('status', models.CharField(choices=[('created', 'Creado'), ('processed', 'Procesado'), ('cancelled', 'Cancelado'), ('deleted', 'Eliminado'), ('error', 'Error')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to='weather.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'location', 'target_date', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_probability', models.FloatField(help_text='Probabilidad de lluvia en porcentaje.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('adverse_probability', models.FloatField(help_text='Probabilidad global de condiciones adversas (%).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('adverse_details', models.JSONField(blank=True, help_text='Detalle de probabilidades por condición adversa.', null=True)),
                ('label', models.CharField(choices=[('favorable', 'Favorable'), ('unfavorable', 'No favorable')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conditions', models.ManyToManyField(blank=True, related_name='forecasts', to='weather.weathercondition')),
                ('event_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='events.eventrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('nasa', 'NASA'), ('model', 'Modelo Estadístico')], max_length=20)),
                ('endpoint', models.URLField(max_length=300)),
                ('request_params', models.JSONField()),
                ('response_status', models.IntegerField(blank=True, help_text='Código HTTP de respuesta (si aplica).', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Tiempo de respuesta en milisegundos.', null=True)),
                ('payload', models.JSONField(blank=True, help_text='Respuesta cruda (JSON) para auditoría.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Detalle en caso de error.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='events.forecastresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel')], default='pdf', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(blank=True, help_text='Hash opcional para verificar integridad.', max_length=64)),
                ('event_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.eventrequest')),
            ],
        ),
    ]
