# Generated by Django 5.2.8 on 2025-11-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('weather', '0002_weatherquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='weather_query',
            field=models.ForeignKey(blank=True, help_text='La consulta de clima que motivó este evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_events', to='weather.weatherquery'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='activity',
            field=models.CharField(help_text='Ej: desfile, concierto...', max_length=200),
        ),
    ]
